## RabbitMQ configuration for Subly
default_vhost = /
log.console = true
log.console.level = info

## Reasonable defaults for a dev/staging environment
vm_memory_high_watermark.relative = 0.6
disk_free_limit.absolute = 1GB
